### ISSUE TITLE
getting an error event instead of a response event

### ISSUE THREAD

**Issue by bringingkatigbak** [TooTallNate/node-modbus-stack#5]
Short version is that I am trying to create a client (master) to read holding registers on a server (slave) via modbus. I am getting the following error event: Error: connect ECONNREFUSED
        at errnoException (net.js:776:11)
        at Object.afterConnect [as oncomplete](net.js:767:19).

Long version is here:
http://stackoverflow.com/questions/18989638/node-modbus-stack-econnrefused

any guidance would be appreciated, I am kind of new to this area of development.

**Comment by davidfungf** [comment]
I am the beginner on Node.js. May I have a complete example of the modbus master (client)?
